### ISSUE TITLE
로그인이 되지 않는 문제를 해결한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#197]
현상: 로그인이 되지 않는다.
재현 스텝: 내 지원서
예상되는 원인: `applicant.email`이 `null`이다.
스크린샷:

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method apply.security.JwtTokenProvider.createToken, parameter payload
at apply.security.JwtTokenProvider.createToken(JwtTokenProvider.kt)
at apply.application.ApplicantAuthenticationService.generateTokenByLogin(ApplicantAuthenticationService.kt:26)
at apply.application.ApplicantAuthenticationService$$FastClassBySpringCGLIB$$199dee39.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
```

**Comment by woowahan-pjs** [comment]
### 문제

JPA로 생성하는 인스턴스의 초기화 블록(initializer block)이 작동하지 않는다.

### 해결 방법

아래 두 가지 방법 중 하나를 선택할 수 있다.

1. **초기화 블록을 사용하지 않는다.**

```kotlin
// AS-IS
@Transient
val name: String = information.name

// TO-BE
val name: String
    get() = information.name
```

2. _`invokeInitializers` 옵션을 `true`로 둔다._ (아마도)

### 원인

JPA를 함께 사용하기 위해서는 매개 변수가 없는 생성자가 필요하다. (JSR 338)

> The entity class must have a no-arg constructor. The entity class may have other constructors as well.
The no-arg constructor must be public or protected.

기본적으로 불변을 지향하는 코틀린의 프로그래밍 스타일은 매개 변수가 없는 생성자를 만드는 것이 매우 번거롭다. 그렇기에 코틀린에서는 다양한 컴파일러 플러그인을 지원한다. (`all-open`, `no-arg` 등) 특히 `no-arg`를 감싸고 있는 `kotlin-jpa`는 `@Entity`와 `@Embeddable`, `@MappedSuperclass`가 붙은 클래스에 한해 매개 변수가 없는 생성자를 자동으로 생성한다. 이때 만들어지는 생성자는 직접 접근할 수 없고 Java 리플렉션을 사용하여 접근할 수 있다.

아래는 실제 생성되는 클래스 파일을 Java로 역컴파일한 코드이며 초기화 블록의 코드가 존재하지 않음을 알 수 있다.

```java
@Entity
public final class Applicant extends BaseEntity {

    ...

    public Applicant() {
        super();
    }
}
```

`no-arg`에서 생성하는 생성자를 (코틀린의 관점에서) 합성 생성자(synthetic constructor)라고 부른다.

### 참고 자료

- https://kotlinlang.org/docs/reference/compiler-plugins.html#no-arg-compiler-plugin
- https://blog.junu.dev/37
- https://stackoverflow.com/questions/58993196/kotlin-noarg-plugin-constructor-only-accessible-by-java-reflection
- https://youtrack.jetbrains.com/issue/KT-16692
- https://youtrack.jetbrains.com/issue/KT-27902
- https://youtrack.jetbrains.com/issue/KT-33502
- https://youtrack.jetbrains.com/issue/KT-36944
- https://blog.naver.com/tommybee/220406497643
- https://blog.frankel.ch/synthetic
- https://www.geeksforgeeks.org/constructor-issynthetic-method-in-java-with-examplesx
