### ISSUE TITLE
JUnit 5 -> Kotest로 마이그레이션한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#529]
- [x] #533
   - https://kotest.io/docs/framework/testing-styles.html
   - > Some teams prefer to mandate usage of a single style, others mix and match. There is no right or wrong - do whatever feels right for your team.
- [x] #534
- [x] #535
   - Kotest 의존성을 추가한다.
- [x] #536 

관련 이슈: #63

**Comment by woowahan-pjs** [comment]
https://github.com/woowacourse/service-apply/issues/533#issuecomment-1175040962 에 이어 작성합니다.

- 코틀린을 사용하더라도 JUnit, AssertJ, Mockito 등을 사용할 수 있다.
- Kotest, MockK는 Kotlin DSL을 활용하여 코틀린 스타일로 코드를 작성할 수 있다.
- 코틀린 스타일 코드와 자바 스타일 테스트 코드의 혼합을 방지할 수 있다.
   - `assertThat(true).isTrue()` vs `assertThat(true).isTrue`
   - > 여러 사람이 함께 작업하는 코드에는 자유로운 표현방식보다는 약간의 제약을 가하는 표현방식을 사용해야 한다고 생각한다.
- Kotest와 같은 프레임워크의 강력한 기능을 활용할 수 있다.
   - [kotest-framework-datatest](https://kotest.io/docs/framework/datatesting/data-driven-testing.html)
   - [kotest-property](https://kotest.io/docs/proptest/property-based-testing.html)
- JUnit을 사용하면 코틀린 스타일의 테스트 코드를 작성하기가 어렵다.
- MockK 단점: [Why is mocking so slow to start in Kotlin?](https://stackoverflow.com/questions/62208145/why-is-mocking-so-slow-to-start-in-kotlin)
- [Mocking and Kotest](https://kotest.io/docs/framework/integrations/mocking.html)
- 무조건 Kotest나 MockK를 도입하기보다는 팀의 코틀린 숙련도와 상황을 고려해야 한다.

**Comment by woowahan-pjs** [comment]
[Kotest Spring extension](https://kotest.io/docs/extensions/spring.html)을 사용한 예

```kotlin
@Transactional
@SpringBootTest
class LanguageServiceTest(
    private val languageService: LanguageService
) : StringSpec({
    extensions(SpringExtension)

    "언어를 추가한다." {
        val language = languageService.create(code = "ko", name = "한국어")
        assertSoftly(language) {
            id shouldNotBe 0
            code shouldBe "ko"
            name shouldBe "한국어"
        }
    }
})
```

**Comment by woowahan-pjs** [comment]
1. Kotest 5는 코틀린 1.6 이상에서 작동한다. Kotest 내에서 코틀린 1.6의 `DurationUnit`을 사용한다.
   - https://kotest.io/docs/changelog.html#500-november-2021
   - > Kotlin 1.6 is now the minimum supported version

```
java.lang.NoClassDefFoundError: kotlin/time/DurationUnit
	at io.kotest.engine.spec.interceptor.SpecFinishedInterceptor.intercept-0E7RQCE(SpecFinishedInterceptor.kt:22)
	at io.kotest.engine.spec.interceptor.SpecFinishedInterceptor$intercept$1.invokeSuspend(SpecFinishedInterceptor.kt)
	...
```

2. Kotest 5는 내부적으로 코틀린 코루틴 1.6 이상을 사용한다. 스프링 부트는 2.7.0 버전부터 코틀린 코루틴 버전 1.6.1을 관리한다. 따라서 스프링 부트 2.6.x 버전까지는 `kotlin-coroutines.version`을 1.6.0으로 지정해야 한다.

```gradle
extra["kotlin-coroutines.version"] = "1.6.0"
```

- https://docs.spring.io/spring-boot/docs/2.7.0/reference/html/dependency-versions.html
- `https://github.com/kotest/kotest/issues/2782`

```
java.lang.ClassNotFoundException: kotlinx.coroutines.test.TestDispatcher
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	...
```

3. `AnnotationSpec`에서 `@Nested`를 사용할 수 없다.
   - Kotest 5에서 `@Nested`을 지원한다고 하였지만 `https://github.com/kotest/kotest/commit/69eea2d50067c6fa309fbad568d770c5e861a439`에서 주석 처리되었다.
   - > Added support for `@Nested` in AnnotationSpec
   - `https://github.com/kotest/kotest/issues/2367`
   - `https://github.com/kotest/kotest/issues/3103`

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	...
```
