### ISSUE TITLE
스프링 부트 버전을 2.7.15로 올린다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#565]
관련 이슈: woowacourse-projects/nextstep#938 #563 #529

**Comment by woowahan-pjs** [comment]
## 2.4.x

_현재 서비스에 영향을 준 것만 나열했으므로 추가 정보를 원하면 아래 참고 자료를 읽어 보시기 바랍니다._

- 버전 뒤의 'RELEASE' 제거 (e.g. `2.4.0.RELEASE` -> `2.4.0`)
- `org.springframework.boot:spring-boot-starter-test`에서 JUnit 5의 빈티지 엔진(`org.junit.vintage:junit-vintage-engine`)을 제거
- **프로퍼티 파일을 처리하는 방식이 실행 환경 기반 선언에서 기능 중심의 모듈식 선언으로 변경되었다.**
   - 각 기능에 대한 프로퍼티를 모아서 실행 환경에 필요한 모듈을 그룹화하는 방법이라고 생각하면 좋을 것 같다.
   - 프로필별 파일(profile specific resource)에서 `spring.profiles.include`를 더 이상 사용할 수 없다.
   - **`spring.config.use-legacy-processing`을 추가하면 이전 방식으로 처리할 수 있다.**
- **인메모리 모드의 데이터베이스만 임베디드 데이터베이스가 있는 것으로 간주**하므로 파일(로컬) 모드 및 서버 모드에는 다음과 같은 변경 사항이 적용된다.
   - `spring.datasource.username`은 `sa`로 자동 설정되지 않으므로 수동으로 설정해야 한다.
   - `schema.sql`, `data.sql`을 사용하여 시작 시 초기화하려면 `spring.datasource.initialization-mode`를 설정해야 한다.
- MockMvc DSL에서 `isOk` 등 기존 자바 클래스 `StatusResultMatchers`에서 제공하는 함수를 `StatusResultMatchersDsl`을 통해 제공한다.
   - **`StatusResultMatchers`는 자바 클래스이므로 프로퍼티 호출과 함수 호출 모두 가능하였는데, 함수로 호출하도록 통일하였다.**
   - `https://github.com/spring-projects/spring-framework/issues/24103`
   - _[MockMvc DSL](https://docs.spring.io/spring-framework/reference/languages/kotlin/web.html#mockmvc-dsl)에서 `isOk`를 `isOk()`로 변경해야 하지 않을까?_

### 참고 자료

- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes
- https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide
- https://luvstudy.tistory.com/130
- https://honeymon.io/tech/2021/01/16/spring-boot-config-data-migration.html

```
14:01:30.602 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.boot.context.config.InvalidConfigDataPropertyException: Property 'spring.profiles.include' imported from location 'class path resource [application-local.properties]' is invalid in a profile specific resource [origin: class path resource [application-local.properties] - 11:25]
	at org.springframework.boot.context.config.InvalidConfigDataPropertyException.lambda$throwOrWarn$1(InvalidConfigDataPropertyException.java:125)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.springframework.boot.context.config.InvalidConfigDataPropertyException.throwOrWarn(InvalidConfigDataPropertyException.java:122)
	at org.springframework.boot.context.config.ConfigDataEnvironment.checkForInvalidProperties(ConfigDataEnvironment.java:361)
	at org.springframework.boot.context.config.ConfigDataEnvironment.applyToEnvironment(ConfigDataEnvironment.java:325)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:233)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:375)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
	at apply.ApplicationKt.main(Application.kt:17)
```

**Comment by woowahan-pjs** [comment]
## 2.5.x

_현재 서비스에 영향을 준 것만 나열했으므로 추가 정보를 원하면 아래 참고 자료를 읽어 보시기 바랍니다._

- `getOne()` -> `getById()`
   - **인터페이스에 선언된 `getById()`는 확장 함수보다 호출 우선순위가 높으므로 기존 확장 함수 `getById()`의 이름을 변경해야 한다.**
      - `https://github.com/spring-projects/spring-data-jpa/issues/1697`
   - 이후 버전에서는 `getById()`가 `getReferenceById()`로 다시 변경된다. 이렇게 할 거라면 함수 이름을 조금 더 신중하게 변경했다면 어땠을까?
      - `https://github.com/spring-projects/spring-data-jpa/issues/2232`
- SQL 스크립트 기반 데이터 초기화 작동 방식 변경
   - https://wildeveloperetrain.tistory.com/228

### 참고 자료

- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes

---

### `getOrThrow()`

- 기존 확장 함수 `getById()`의 이름을 바꾸기 위해 여러 함수 이름이 제안되었다. 실제 클라이언트에서 사용할 코드를 기준으로 함수 이름 후보는 아래와 같았다.
   1. `recruitmentRepository[id]`
   2. `recruitmentRepository.get(id)`
   3. `recruitmentRepository.getOrThrow(id)`
   4. `recruitmentRepository.getByIdOrThrow(id)`
   5. `recruitmentRepository.findByIdOrThrow(id)`
   6. `recruitmentRepository.retrieveById(id)`
   7. `recruitmentRepository.fetchById(id)`
   8. `recruitmentRepository.loadById(id)`
- **그 결과 `getOrThrow()`가 선택되었으며 이유는 아래와 같다.**
   1. 'retrieve', 'fetch', 'load'와 같은 좋은 동사를 추천받았지만, [Spring Data에서 지원](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-keywords)하는 것과 최대한 유사한 키워드를 사용하고 싶었다.
   2. 'find'로 `Optional`과 nullable 타입을, 'get'으로 non-null 타입을 표현하고 싶었다. (https://tuhrig.de/find-vs-get)
   3. 그래서 처음에는 `get()`을 선택했지만,
      - 연산자 오버로딩은 자바 코딩에 익숙한 개발자들에게는 꺼려지는 것 같았다.
      - 연산자 오버로딩 없이 `get()`을 사용하려고 했을 때 [MockK가 이미 `get()`을 선점](https://github.com/mockk/mockk/blob/master/modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt#L2082-L2083)하고 있었기 때문에 테스트 코드에서 `get()`을 스텁하는 데 어려움을 겪었다.
   4. 또한 ChatGPT도 예외가 발생할 가능성을 더 정확하게 반영하는 함수 이름(`retrieveById()`, `getOrThrow()`)을 권장했다.
   5. [grep.app](https://grep.app)에서도 검색해 보니 `retrieveById()`보다 `getOrThrow()`가 훨씬 많이 사용되는 것으로 나타났다.
      - https://grep.app/search?q=retrieveById&filter[lang][0]=Java&filter[lang][1]=Kotlin
      - https://grep.app/search?q=getOrThrow&filter[lang][0]=Java&filter[lang][1]=Kotlin
         - 코틀린 API에서 `getOrThrow()`를 많이 사용하고 있다.

**Comment by woowahan-pjs** [comment]
## 2.6.x

_현재 서비스에 영향을 준 것만 나열했으므로 추가 정보를 원하면 아래 참고 자료를 읽어 보시기 바랍니다._

- 요청 경로를 핸들러 매핑에 일치시키는 기본 전략이 `AntPathMatcher`에서 `PathPatternParser`로 변경되었다.
   - 예를 들어, 더 정확하게 일치시키려면 `authorizeRequests.mvcMatchers("hello").permitAll()`에서 `authorizeRequests.mvcMatchers("/hello").permitAll()`로 변경해야 한다. (앞의 /에 유의)
- **Flyway 버전이 7.x에서 8.0.5로 변경되었다.**
   - Flyway Community Edition이 5년이 넘은 데이터베이스 버전에 대한 지원을 중단하였다.
      - https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html#ReleaseNotesforFlywayEngine-Flyway8.0.0-beta1(2021-09-14)
      - MySQL 5.7이 이에 해당한다. MySQL 버전을 8.x로 올린다.
         - `https://github.com/flyway/flyway/commit/4622cee057c855a718533d60aecb2c3e21960a5f`
         - `https://github.com/flyway/flyway/issues/3319`
         - #724 
      - **MySQL 버전을 8.x로 올리기 전까지 Flyway 버전을 7.x로 유지한다.**
- `Resources`를 직접 주입하는 것은 더 이상 작동하지 않으므로 필요한 경우 `WebProperties`를 주입해야 한다.
   - `https://github.com/spring-projects/spring-boot/issues/28762`
   - 이 부분에서 Vaadin에 문제가 있었고, 정적 리소스를 찾을 수 없는 문제가 발생했다.
      - `https://github.com/vaadin/spring/issues/941`
      - `https://github.com/vaadin/spring/issues/953`
      - **Vaadin 버전을 14.3.3에서 14.8.20으로 변경한다.**

### 참고 자료

- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes
- https://vaadin.com/docs/latest/configuration/source-control

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException: Flyway Teams Edition or MySQL upgrade required: MySQL 5.7 is no longer supported by Flyway Community Edition, but still supported by Flyway Teams Edition.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1156)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:910)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:423)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at apply.ApplicationKt.main(Application.kt:17)
Caused by: org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException: Flyway Teams Edition or MySQL upgrade required: MySQL 5.7 is no longer supported by Flyway Community Edition, but still supported by Flyway Teams Edition.
	at org.flywaydb.core.internal.database.base.Database.ensureDatabaseNotOlderThanOtherwiseRecommendUpgradeToFlywayEdition(Database.java:126)
	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.ensureSupported(MySQLDatabase.java:251)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:188)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 18 common frames omitted
```

---

### Vaadin 14.8.20

- Vaddin 14의 최신 버전은 14.10.6이지만 14.8.20을 선택하였다.
- Vaddin 14.8.20에는 Vaadin Flow 2.7.23이 포함되어 있으며, Vaddin 14.9.0부터는 Vaadin Flow 2.8.0이 포함되어 있다.
   - _모듈 간 버전이 매우 헷갈리는데 다행히 Vaadin 23부터는 Flow의 메이저 버전과 마이너 버전이 플랫폼 버전과 일치한다._
- Vaadin Flow 2.8.0부터 `tsconfig.json`, `types.d.ts` 파일 생성 여부를 결정하는 로직이 변경되어 현재 프로젝트에서는 무조건 해당 파일이 생성된다.
   - **현재 프로젝트의 디렉터리 구조로 인해 타입스크립트 기반 클라이언트 코드에도 영향을 미치기 때문에 자동으로 생성되지 않는 Vaddin 14.8.20을 사용한다.**
      - 현재 구조는 백엔드 디렉터리 아래에 프론트엔드 디렉터리가 있으며, 두 디렉터리가 서로 영향을 주지 않도록 같은 수준으로 개선한다.
      - #725 
   - _문제를 찾는 것이 매우 어려웠다. 왜 따로 해결하지 않고 다른 문제를 해결하는 PR에 포함했을까?_
      - `https://github.com/vaadin/flow/issues/14733`
      - `https://github.com/vaadin/flow/pull/14871` 

### 참고 자료

#### Vaadin Flow 2.8.0

TaskGenerateTsFiles.java#L54-L61

```java
/**
 * Generate typescript config if it doesn't exist.
 *
 * @return if typescript config file should be created
 */
protected boolean shouldGenerate() {
    return !new File(npmFolder, TSCONFIG_JSON).exists();
}
```

#### Vaadin Flow 2.7.23

TaskGenerateTsFiles.java#L57-L65

```java
/**
 * Only generate if there exists typescript modules in the project.
 *
 * @return if we have modules for typescript files
 */
protected boolean shouldGenerate() {
    return modules.stream().filter(file -> file.endsWith(".ts"))
            .count() >= 1;
}
```

```
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts(14,37)
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              :       TS2344: Type '"email" | "password"' does not satisfy the constraint '"id" | "name" | "email"'.
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              :   Type '"password"' is not assignable to type '"id" | "name" | "email"'.
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts(18,44)
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              :       TS2344: Type '"name" | "email" | "password" | "birthday"' does not satisfy the constraint '"id" | "name" | "email"'.
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              :   Type '"password"' is not assignable to type '"id" | "name" | "email"'.
2023-08-24 16:52:14.259 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts(52,3)
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              :       TS2339: Property 'phoneNumber' does not exist on type 'FetchRegisterRequest'.
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts(53,3)
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              :       TS2339: Property 'gender' does not exist on type 'FetchRegisterRequest'.
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts(54,3)
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              :       TS2339: Property 'birthday' does not exist on type 'FetchRegisterRequest'.
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts(55,3)
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              :       TS2339: Property 'password' does not exist on type 'FetchRegisterRequest'.
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/api/user.ts(77,26)
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              :       TS2345: Argument of type 'unknown' is not assignable to parameter of type 'Date'.
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/hooks/useRecruitList.ts
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/hooks/useRecruitList.ts(2,35)
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              :       TS7016: Could not find a declaration file for module './useRecruitmentContext'. '/Users/jaesung/Dev/woowabros/service-apply/frontend/src/hooks/useRecruitmentContext.js' implicitly has an 'any' type.
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/mock/autoGradeHandler.ts
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/mock/autoGradeHandler.ts(7,58)
2023-08-24 16:52:14.260 ERROR 15593 --- [        webpack] dev-webpack                              :       TS6133: 'req' is declared but its value is never read.
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/mock/autoGradeHandler.ts
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/mock/autoGradeHandler.ts(10,50)
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              :       TS6133: 'req' is declared but its value is never read.
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/mock/autoGradeHandler.ts
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/mock/autoGradeHandler.ts(20,6)
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              :       TS6133: 'req' is declared but its value is never read.
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              : ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/mock/autoGradeHandler.ts
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              : [tsl] ERROR in /Users/jaesung/Dev/woowabros/service-apply/frontend/src/mock/autoGradeHandler.ts(28,6)
2023-08-24 16:52:14.261 ERROR 15593 --- [        webpack] dev-webpack                              :       TS6133: 'req' is declared but its value is never read.
```

**Comment by woowahan-pjs** [comment]
### 문제

Vaadin 14.8.20에서 `DateTimePicker`의 `LocalDateTime` 변환에서 마이크로초가 생략되어 테스트가 실패한다.

```
data class diff for apply.application.RecruitmentData
├ startDateTime: expected:<2022-08-28T18:35:18.520409> but was:<2022-08-28T18:35:18.520>
└ endDateTime: expected:<2024-08-28T18:35:18.520447> but was:<2024-08-28T18:35:18.520>
```

### 해결 방법

1. **확인할 값(expected)에서 마이크로초를 자른다.**
2. Vaadin 버전을 14.7.1 이상으로 올리지 않는다.

### 원인

- [Vaadin 14.7.1](https://github.com/vaadin/flow-components/releases/tag/14.7.1) 이상에서 `DateTimePicker`의 시간 정밀도가 밀리초로 변경되었다.
   - `https://github.com/vaadin/flow-components/pull/2099`
   - `https://github.com/vaadin/flow-components/issues/1428`

**Comment by woowahan-pjs** [comment]
## 2.7.x

_현재 서비스에 영향을 준 것만 나열했으므로 추가 정보를 원하면 아래 참고 자료를 읽어 보시기 바랍니다._

- Flyway 버전이 8.0.5에서 8.5로 변경되었다.
   - 사용 중인 데이터베이스에 적합한 모듈을 추가해야 한다. 이 부분은 #724 작업 시 다룬다.
      - `flyway-firebird` (Firebird)
      - `flyway-mysql` (MariaDB and MySQL)
      - `flyway-sqlserver` (SQL Server)
- **H2 버전이 1.4.200에서 2.1.120로 변경되었다.**
   - http://www.h2database.com/html/migration-to-v2.html
- **`WebSecurityConfigurerAdapter`에서 `SecurityFilterChain`으로 마이그레이션**
   - https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
   - `WebSecurityConfigurerAdapter`는 Bean 생성, Bean 주입 등에 설계상 결함이 있어서 이를 수정하고 다른 구성과 작동 방식을 통일하기 위해 Bean을 생성하도록 변경하였다.
      - `https://github.com/spring-projects/spring-security/issues/10822`
- `mysql:mysql-connector-java` -> `com.mysql:mysql-connector-j`
   - 기존 `mysql:mysql-connector-java`의 `groupId`는 오랫동안 `mysql`이라는 한 단어로 유지되어 온 레거시 형태인데, 이를 역도메인 형태인 `com.mysql`로 변경했다.
      - https://blogs.oracle.com/mysql/post/mysql-connectorj-has-new-maven-coordinates
- `getById()` -> `getReferenceById()`
   - `getOne()` -> `getById()`([2.4.15](https://github.com/spring-projects/spring-data-jpa/releases/tag/2.4.15)) -> `getReferenceById()`([2.7.0](https://github.com/spring-projects/spring-data-jpa/releases/tag/2.7.0-M1))

### 참고 자료

- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes

---

### H2 2.1.120

- 더 많은 표준 SQL 키워드가 추가되었다.
   - http://www.h2database.com/html/advanced.html#keywords
   - **H2 2.0.202부터 키워드로 `USER`가 추가되었다.**
      - `https://github.com/h2database/h2database/pull/2645`
      - `https://github.com/h2database/h2database/issues/3363`
      - `https://github.com/h2database/h2database/issues/3591`
   - **`jdbc:h2:./test;NON_KEYWORDS=USER`와 같은 `NON_KEYWORDS` 설정을 추가하여 임시로 해결할 수 있다.**
      - https://h2database.com/html/commands.html#set_non_keywords
- 문자열이 고정 길이보다 짧은 경우 공백 문자가 오른쪽에 채워진다.
   - https://h2database.com/html/datatypes.html#character_type
   - `https://github.com/h2database/h2database/issues/2407`
   - 예를 들어 `char(40)`의 빈 공간을 채운다. (e.g. `"commit1                                 "`)
   - **MariaDB, MySQL 등 일부 호환 모드에서는 CHAR 값 오른쪽 공백이 자른다.**
      - https://h2database.com/html/features.html#compatibility
