### ISSUE TITLE
Gradle 버전을 7.6.2로 올린다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-apply#707]
Gradle 버전 변경으로 인한 Gradle 플러그인 충돌이 많이 발생하므로 이를 해결하며 진행한다.

### Java

- Java 버전을 17 이상으로 변경하려면 Gradle 버전을 7.3 이상으로 올려야 한다.
- https://docs.gradle.org/current/userguide/compatibility.html

### 스프링 부트

- 스프링 부트 2.7.14에는 Gradle 6.8, 6.9, 7.x 또는 8.x가 필요하다.
- 스프링 부트 3.1.2에는 Gradle 7.5 이상 또는 8.x가 필요하다.
- https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle

**Comment by woowahan-pjs** [comment]
- [x] 6.9.2 -> 7.0
   - https://docs.gradle.org/current/userguide/upgrading_version_6.html
   - `isAllowInsecureProtocol` 추가
      - https://stackoverflow.com/questions/68585885/allow-insecure-protocols-android-gradle
      - https://docs.gradle.org/6.0/release-notes.html#security-improvements
      - `https://github.com/gradle/gradle/pull/15670`
- [x] 7.0 -> 7.6.2
   - https://docs.gradle.org/7.6.2/userguide/upgrading_version_7.html
- [ ] 7.6.2 -> 8.2.1

**Comment by woowahan-pjs** [comment]
## 7.6.2 -> 8.2.1

현재 버전 구성에서는 실패한다.

### 문제

스프링 부트 2.3.3에서 Gradle 버전을 8.2.1로 올리면 아래 예외가 발생한다.

```
./gradlew wrapper --gradle-version=8.2.1 --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
org/gradle/api/plugins/MavenPlugin
> org.gradle.api.plugins.MavenPlugin

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
java.lang.NoClassDefFoundError: org/gradle/api/plugins/MavenPlugin
        at org.springframework.boot.gradle.plugin.MavenPluginAction.getPluginClass(MavenPluginAction.java:41)
        at org.springframework.boot.gradle.plugin.SpringBootPlugin.registerPluginActions(SpringBootPlugin.java:123)
        at org.springframework.boot.gradle.plugin.SpringBootPlugin.apply(SpringBootPlugin.java:93)
        at org.springframework.boot.gradle.plugin.SpringBootPlugin.apply(SpringBootPlugin.java:45)
```

### 해결 방법

1. 스프링 부트 버전을 2.4.2 이상으로 올린다.
2. **Gradle 버전을 8 이상으로 올리지 않는다.**

### 원인

- `maven` 플러그인이 Gradle 7에서 제거될 예정이었으나 실제로는 Gradle 8부터 존재하지 않는다.
   - `https://github.com/gradle/gradle/issues/15606`
- 스프링 부트 플러그인은 내부적으로 `maven` 플러그인을 사용하기 때문에 예외가 발생한다.
    - `https://github.com/gradle/gradle/issues/24297`
- 스프링 부트 2.4.2부터는 플러그인이 존재하지 않아 예외가 발생해도 무시하도록 변경되었다.
    - `https://github.com/spring-projects/spring-boot/issues/24526`
    - `https://github.com/spring-projects/spring-boot/issues/25267`
